In [1]:
import numpy as np
import pandas as pd
import re
import pickle

In [6]:
with open('./with_name/LDA_clean_scaled_final.pkl', 'rb') as f:
    df_with = pickle.load(f)

In [7]:
df_with

,뉴스제목,주가변동,문서 번호,가장 비중이 높은 토픽,가장 높은 토픽의 비중,각 토픽의 비중,str_len
0,LG생활건강 숨 로시크숨마 황제의 빛 에디션 선봬,1,0,1,0.9640,"[(0, 0.035994086), (1, 0.96400595)]",27
6,SK에너지GS칼텍스 공유경제동반성장 다 잡았다,0,6,0,0.9211,"[(0, 0.9211468), (1, 0.078853145)]",25
9,CNN 한국 대표 혁신 기업으로 삼성전자 소개,0,9,0,0.9234,"[(0, 0.92337716), (1, 0.0766229)]",25
10,한경로보뉴스 맥쿼리인프라 주 신고가 경신,1,10,1,0.9390,"[(0, 0.06101659), (1, 0.9389834)]",22
12,현대모비스 자율주행 첨단 센서로 차량내부 안전시스템 구축,0,12,0,0.9572,"[(0, 0.9572409), (1, 0.042759143)]",31
...,...,...,...,...,...,...,...
611457,한샘 분기 이후 실적 턴어라운드 예상 KTB,0,611457,0,0.7651,"[(0, 0.76507807), (1, 0.2349219)]",24
611458,한미약품 임직원 자녀 위한 꿈나무어린이집 개원,1,611458,1,0.5119,"[(0, 0.4881193), (1, 0.51188064)]",25
611461,단독 백신 대란에SK바이오사이언스 독감 접고 코로나 백신 생산 올인,1,611461,1,0.9454,"[(0, 0.05455975), (1, 0.9454403)]",37
611466,CJ제일제당 글로벌 수준 경영 인프라 구축,0,611466,0,0.5721,"[(0, 0.57210296), (1, 0.42789704)]",23
611472,KT주도 클라우드 원팀에 한컴 등 개 기업기관 합류,0,611472,0,0.5888,"[(0, 0.58883274), (1, 0.4111673)]",28

In [10]:
df_with.drop(['문서 번호', '가장 비중이 높은 토픽', '가장 높은 토픽의 비중', '각 토픽의 비중', 'str_len'], axis = 1)

                                         뉴스제목  주가변동
0                 LG생활건강 숨 로시크숨마 황제의 빛 에디션 선봬     1
6                   SK에너지GS칼텍스 공유경제동반성장 다 잡았다     0
9                   CNN 한국 대표 혁신 기업으로 삼성전자 소개     0
10                     한경로보뉴스 맥쿼리인프라 주 신고가 경신     1
12            현대모비스 자율주행 첨단 센서로 차량내부 안전시스템 구축     0
...                                       ...   ...
611457               한샘 분기 이후 실적 턴어라운드 예상 KTB     0
611458              한미약품 임직원 자녀 위한 꿈나무어린이집 개원     1
611461  단독 백신 대란에SK바이오사이언스 독감 접고 코로나 백신 생산 올인     1
611466                CJ제일제당 글로벌 수준 경영 인프라 구축     0
611472           KT주도 클라우드 원팀에 한컴 등 개 기업기관 합류     0

[248282 rows x 2 columns]

In [11]:
from sklearn.model_selection import train_test_split

train_with, test_with = train_test_split(df_with, test_size=.2)

In [12]:
counter = 1
for _, line in train_with.iterrows():

    if line["주가변동"] == 0:
        sen = line["뉴스제목"]
        filename = './with_name/classes_f/train/0/{0:06d}.txt'.format(counter)
        text_file = open(filename, "w", encoding='utf-8')
        text_file.write(sen)
        text_file.close()
    else:
        sen = line["뉴스제목"]
        filename = './with_name/classes_f/train/1/{0:06d}.txt'.format(counter)
        text_file = open(filename, "w", encoding='utf-8')
        text_file.write(sen)
        text_file.close()

    counter += 1

counter = 1
for _, line in test_with.iterrows():

    if line["주가변동"] == 0:
        sen = line["뉴스제목"]
        filename = './with_name/classes_f/test/0/{0:06d}.txt'.format(counter)
        text_file = open(filename, "w", encoding='utf-8')
        text_file.write(sen)
        text_file.close()
    else:
        sen = line["뉴스제목"]
        filename = './with_name/classes_f/test/1/{0:06d}.txt'.format(counter)
        text_file = open(filename, "w", encoding='utf-8')
        text_file.write(sen)
        text_file.close()

    counter += 1